import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import courseRoutes from './course.routes';
import chapterRoutes from './chapter.routes';
import lessonRoutes from './lesson.routes';
import quizRoutes from './quiz.routes';
import attemptRoutes from './attempt.routes';
import assignmentRoutes from './assignment.routes';
import submissionRoutes from './submission.routes';
import certificateRoutes from './certificate.routes';
import gamificationRoutes from './gamification.routes';
import notificationRoutes from './notification.routes';
import aiRoutes from './ai.routes';
import placementRoutes from './placement.routes';
import communityRoutes from './community.routes';
import attendanceRoutes from './attendance.routes';
import adminRoutes from './admin.routes';
import newsRoutes from './news.routes';
import categoryRoutes from './category.routes';
import codingRoutes from './coding.routes';
import profileRoutes from './profile.routes';
import showcaseRoutes from './showcase.routes';
import careerMentorRoutes from './careerMentor.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/courses', courseRoutes);
router.use('/chapters', chapterRoutes);
router.use('/lessons', lessonRoutes);
router.use('/quizzes', quizRoutes);
router.use('/attempts', attemptRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/submissions', submissionRoutes);
router.use('/certificates', certificateRoutes);
router.use('/gamification', gamificationRoutes);
router.use('/notifications', notificationRoutes);
router.use('/ai', aiRoutes);
router.use('/placement', placementRoutes);
router.use('/community', communityRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/admin', adminRoutes);
router.use('/news', newsRoutes);
router.use('/categories', categoryRoutes);
router.use('/coding', codingRoutes);
router.use('/profile', profileRoutes);
router.use('/showcase', showcaseRoutes);
router.use('/career-mentor', careerMentorRoutes);

export default router;
